name: my_maker_video
description: Create videos from image sequences, add watermarks, reduce video quality, and convert videos to GIFs with FFmpeg.
version: 0.2.0-dev.1
repository: https://github.com/ngmduc2012/my_maker_video
funding:
  - https://buymeacoffee.com/ducmng12g
  - https://ko-fi.com/I2I81AEJG8

environment:
  sdk: ^3.13.1
  flutter: '>=3.47.1'

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter_new: ^4.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.wongcoupon.my_maker_video.my_maker_video
        pluginClass: MyMakerVideoPlugin
      ios:
        pluginClass: MyMakerVideoPlugin

screenshots:
  - description: "author Wong Nguyen"
    path: avatar.png

topics:
  - ffmpeg
  - gif
  - video-processing
  - watermark
