name: my_maker_video
description: "create images to video very fast,add watermark for video, reduce quality of video, video to gif"
version: 0.0.2+1
repository: https://github.com/ngmduc2012/my_maker_video
funding:
  - https://buymeacoffee.com/ducmng12g
  - https://ko-fi.com/I2I81AEJG8

environment:
  sdk: ^3.5.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter_full_gpl: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.wongcoupon.my_maker_video.my_maker_video
        pluginClass: MyMakerVideoPlugin
      ios:
        pluginClass: MyMakerVideoPlugin

screenshots:
  - description: "author Wong Nguyen"
    path: avatar.png

topics:
  - log
  - color
  - save-file
  - popup-realtime-log
  - video-processing